FROM python:3.7-buster

WORKDIR /app

# install requirements
ADD requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "src.app:app", "--reload"]